version: "3.8"

services:
  redis:
    image: redis/redis-stack:latest
    networks:
      - app
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    env_file:
      - .env
    networks:
      - app
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

  api:
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app/
    networks:
      - app
    ports:
      - 8888:8000
    depends_on:
      - db

networks:
  app:
    driver: bridge
