"""empty message

Revision ID: e414f4c5371c
Revises: 457edfdfafa8
Create Date: 2023-03-28 09:46:04.176577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e414f4c5371c'
down_revision = '457edfdfafa8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profiles_username_fkey', 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['username'], ['username'], ondelete='CASCADE')
    op.drop_index('ix_users_username', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key('profiles_username_fkey', 'profiles', 'users', ['username'], ['username'])
    # ### end Alembic commands ###
